export const REQUEST_LIST_USER = 'REQUEST_LIST_USER';
export const REQUEST_LIST_USER_SUCCESS = 'REQUEST_LIST_USER_SUCCESS';
export const REQUEST_LIST_USER_FAILED = 'REQUEST_LIST_USER_FAILED';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';