export const REQUEST_LIST_TODOS = 'REQUEST_LIST_TODOS';
export const REQUEST_LIST_TODOS_SUCCESS = 'REQUEST_LIST_TODOS_SUCCESS';
export const REQUEST_LIST_TODOS_FAILED = 'REQUEST_LIST_TODOS_FAILED';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
